server: 
  port: 7003
  #单机版
#eureka:
#  server: 
#    enable-self-preservation: true #禁用自我保护模式false,开启true
#  instance:
#    hostname: 127.0.0.1 #eureka服务端的实例名称
#  client:
#    register-with-eureka: false #false表示不向注册中心注册自己。
#    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

      
#集群版
eureka: 
  server: 
    enable-self-preservation: true #禁用自我保护模式false,开启true
  instance:
    hostname: eureka7003.com #Eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://root:root@eureka7001.com:7001/eureka/,http://root:root@eureka7002.com:7002/eureka/

security:
  basic:
    enabled: true
  user:
    name: root #用户名和密码，等会访问的时候，会要求你登录，服务注册的时候也需要带着用户名和密码
    password: root