server: 
 port: 9527

spring: 
  application:
   name: microservicecloud-zuul-gateway
  redis: 
    database: 5
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 3000
    pool:
      max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
      min-idle: 0       # 连接池中的最小空闲连接，默认值也是0
      max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出
eureka: 
 client: 
   service-url: 
     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
 instance:
   instance-id: gateway-9527.com
   prefer-ip-address: true 

zuul: 
  ignored-services: microservicecloud-dept     #只是添加了这一句！！
  routes: 
    dept.serviceId: microservicecloud-dept
    dept.path: /mydept/**

info:
  app.name: hhf-microcloud
  company.name: www.hhf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

security:
  user:
    name: admin
    password: admin
  